"""add recovery password 

Revision ID: 1a0a8c14df77
Revises: f43c4b794fe7
Create Date: 2026-03-19 12:11:23.605487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0a8c14df77'
down_revision: Union[str, Sequence[str], None] = 'f43c4b794fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwordreocovery',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=True),
    sa.Column('expire_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_unique_constraint(None, 'auth', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='unique')
    op.drop_table('passwordreocovery')
    # ### end Alembic commands ###
