""" upgrade table

Revision ID: 234136733ecb
Revises: d65a4150e1ec
Create Date: 2026-03-21 16:25:34.483802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234136733ecb'
down_revision: Union[str, Sequence[str], None] = 'd65a4150e1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index(op.f('ix_provider_provider_id'), 'provider', ['provider_id'], unique=False)
    op.add_column('auth', sa.Column('email', sa.String(), nullable=True))
    op.add_column('auth', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'auth', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='unique')
    op.drop_column('auth', 'name')
    op.drop_column('auth', 'email')
    op.drop_index(op.f('ix_provider_provider_id'), table_name='provider')
    op.drop_table('provider')
    # ### end Alembic commands ###
