"""add email table

Revision ID: d65a4150e1ec
Revises: 1a0a8c14df77
Create Date: 2026-03-19 16:10:01.321060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd65a4150e1ec'
down_revision: Union[str, Sequence[str], None] = '1a0a8c14df77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=True),
    sa.Column('expire_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.drop_table('passwordreocovery')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwordreocovery',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expire_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('passwordreocovery_pkey'))
    )
    op.drop_table('email')
    # ### end Alembic commands ###
