"""empty message

Revision ID: f43c4b794fe7
Revises: 
Create Date: 2026-03-08 21:52:13.982002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43c4b794fe7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='USER', nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notices',
    sa.Column('notice_id', sa.Integer(), sa.Identity(always=False, start=1001, increment=1), nullable=False),
    sa.Column('Type', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('notice_id')
    )
    op.create_table('token',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('user_logs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logs_id', sa.Integer(), sa.Identity(always=False, start=1021, increment=1), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('logs_id')
    )
    op.create_table('complaint',
    sa.Column('ticket_id', sa.Integer(), sa.Identity(always=False, start=201, increment=1), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_complaint_ticket_id'), 'complaint', ['ticket_id'], unique=False)
    op.create_table('epass',
    sa.Column('ticket_id', sa.Integer(), sa.Identity(always=False, start=101, increment=1), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('guest_name', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('arrival', sa.String(), nullable=True),
    sa.Column('departure', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('vehicle_no', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_epass_ticket_id'), 'epass', ['ticket_id'], unique=False)
    op.create_table('personal',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('resident',
    sa.Column('house_no', sa.String(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner')
    )
    op.create_table('vehicle',
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['auth.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner', 'number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('resident')
    op.drop_table('personal')
    op.drop_index(op.f('ix_epass_ticket_id'), table_name='epass')
    op.drop_table('epass')
    op.drop_index(op.f('ix_complaint_ticket_id'), table_name='complaint')
    op.drop_table('complaint')
    op.drop_table('user_logs')
    op.drop_table('token')
    op.drop_table('notices')
    op.drop_table('auth')
    # ### end Alembic commands ###
